name: Paddle Toolbox Test

on: [push, pull_request]

jobs:
  test-pptb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        architecture: ["x64"]
    name: Python ${{ matrix.python-version }} on ${{ matrix.architecture }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        id: poetry-cache
        with:
          path: |
            **/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: |
          poetry install -E paddle

      - name: paddle toolbox test
        run: |
          poetry run pytest -m "not ci_skip"
